name: continuous deployment to dev

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    container: "openjdk:11-slim"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-liceo-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-liceo-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-liceo-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-liceo-wrapper-
      - name: build
        run: ./gradlew clean build

  docker:
    needs: check
    runs-on: ubuntu-latest
    container: "openjdk:11-slim"
    steps:
      - uses: actions/checkout@v2
      - name: Publish latest image to Docker Hub
        env:
          REGISTRY_KEY: ${{ secrets.REGISTRY_KEY }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        run: ./gradlew --stacktrace dockerPush -PregistryUser=$REGISTRY_USER -PregistryKey=$REGISTRY_KEY

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to K8s (dev)
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout restart deployment/liceo
      - name: verify API deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout restart deployment/liceo
      - name: Wait a little bit before restarting front
        run: sleep 15
      - name: Make front be aware of API changes (Hack)
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout restart deployment/patio-front
