name: k8s rollout restart every 8 hours

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: redeploy db
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout restart deployment/liceo-db
      - name: Wait a little bit before restarting web
        run: sleep 15
      - name: redeploy web
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout restart deployment/liceo-web
